### ISSUE TITLE
Current Intentions for Milestone 0.1

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#10]
Since this project has been somewhat revived, these are some of my intentions with this project before release.
- [x] Add currently independent static vehicles to the pack where applicable #7 (Searchlight Done, rest is put in backlog)
- [x] Finish up Fixes and Enhancements for individual weapon systems #2 (Backlog now, but mostly done)
- [x] Replace custom Nunjucks Templating with Binarization + CBA Macros #8 
- [x] Integrate CUP As a dependency #9
- [x] Port back the Assemble Backpack functionality for Applicable Weapons. #11
