### ISSUE TITLE
Ported Content Enhancements Checklist

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#2]
The following changes / enhancements will be applied to the ported RDS Static weapons:
- [x] Apply Project Reality sounds to fitting weapons
- [x] Fix SPG-9 errors
- [x] Simplify config structure. Allow for easy removal of certain weapons, but still keep everything in 1 PBO.
- [x] Fix TOW Falling over.
- [x] Ensure ACE Cargo and Dragging works for Static Weapons
- [x] Make M252 and Podnos compatible with ace_mk6mortar settings
- [x] Tweak Damage Model for each Weapon
- [x] Adjust Turn speed, reload speed and Aiming FOV in static emplacements.
- [x] Normalize Sounds imported from PR to have the same volume as Vanilla content.
- [x] Improve gunner reticles where needed (D-30, M119 for example).
## Damage Model Tweaks
- [x] TOW Missile
- [x] Metis Missile
- [x] SPG-9 Missiles

**Comment by Mallow234** [comment]
I don't think RAM compatibility is neccessary seeing as we're working on our own stuff now

**Comment by ComfyPillow** [comment]
I intend to make the Vanilla Damage model default but have a config flag (rhs_compat in config.json) that if activated applies the required RHS Damage values and entries to weapons that need them.

The idea is that if the flag is active, the mod will be built with RHS Damage config entries built in. This is for the fact that we don't know for how much longer we use RHS, and it's a simple change.

That way, if for whatever possible reason, we'd still have a version which is somewhat compatible with RHS.

``` c++
class RDS_G_30mm_HE: G_40mm_HE {
  whistledist = 5.5;
  caliber = 1.5;
  indirecthit = 10;
  indirecthitrange = 5.5;

  {% if rhs_compat %}
    hit = 20;
    ais_ce_penetrators[] = { "ais_ammo_40mm_HEDP_penetrator" };
  {% else %}
    hit = 35;
  {% endif %}
};
```

Take this code for example. if rhs_compat is defined as true in the config.json, the templating engine will automatically apply the defined RHS Values for the weapons. The good thing about this is that we don't have to play around with replacement configs, and the RHS config values also won't show up in a regular build by default.

Been using the same concept on Kaukmod to "compile" it with certain functionality either enabled or disabled, and my experience has been very positive.

**Comment by Mallow234** [comment]
I guess I can configure the ammo if you wanr

**Comment by ComfyPillow** [comment]
Added ACE Logi Dragging / Cargo to list. May or may not work right now, but need to make sure for every object.

Eventually we have to configure the following ACE config Values:

``` c++
GVAR(size) = 2; // 1 = small, 2 = large
GVAR(canLoad) = 1;
```

Also in ACE 3.4.0 there's a possibility that this will be merged in:

https://github.com/acemod/ACE3/pull/2164

If that happens, all Static Weapons must be configured to make use of this functionality. Probably need to configure the following Values:
- ace_caliber
- magazine model (maybe?)

**Comment by Mallow234** [comment]
Afaik caliber also determines penetration in arma 3 if you're talking about ammo values, so you'll want to take that into account

**Comment by ComfyPillow** [comment]
Thats actually a different value (ace_caliber), which to my understanding determines what caliber the ammo is, mainly for looking if the Magazine is suitable for vehicle rearm.

Mainly a reminder so I don't forget to do this if it gets merged.

**Comment by Kauwgompje** [comment]
Regarding the proper naming scheme for the russian weapons I propose doing "GRAU 'nickname'" where GRAU is the GRAU name and nickname is whatever the most popular name, this could be a production name, actual nickname or model number depending on what is the most recognizable. for example;

Igla would be "9K38 'Igla'"
Zu-23 would be "2A13 'ZU-23-2'" although the official nickname is "Sergey" I feel ZU-23 is more recognizable.

This naming scheme may seem a little arbitrary but I feel this would give it both a standard for naming and a way to recognize weapons by their most popular names, thoughts?

(I have no clue if this is the correct place to put this.)

**Comment by ComfyPillow** [comment]
Putting this in backlog, since not all of those get delivered in the coming release
